import React, { useState, useEffect } from 'react';
import { statementService, transactionService } from '../services/api';
import StatementSelector from '../components/adjunct/StatementSelector';
import LedgerForm from '../components/adjunct/LedgerForm';
import TransactionTable from '../components/adjunct/TransactionTable';
import { UploadCloud } from 'lucide-react';

export default function AdjunctOutlays() {
  const [statements, setStatements] = useState([]);
  const [selectedStatement, setSelectedStatement] = useState(null);
  const [transactions, setTransactions] = useState([]);
  const [categories, setCategories] = useState([]);
  const [isCreating, setIsCreating] = useState(false);
  const [newName, setNewName] = useState("");
  const [formData, setFormData] = useState({ transaction_date: new Date().toISOString().split('T')[0], vendor_raw: '', amount: '', category: '' });

  useEffect(() => { loadData(); }, []);

  const loadData = async () => {
    try {
      const rawStmtData = await statementService.listStatements();
      const rawCatData = await transactionService.getCategories();
      const dataArray = Array.isArray(rawStmtData) ? rawStmtData : (rawStmtData?.data || []);
      const manualOnly = dataArray.filter(s => s.source_type === 'manual');
      setStatements(manualOnly);
      setCategories(rawCatData || []);
    } catch (err) { console.error("Failed to load layout:", err); }
  };

  const handleSelect = async (stmt) => {
    setSelectedStatement(stmt);
    try {
      const txs = await statementService.getStatementTransactions(stmt.id);
      setTransactions(txs || []);
    } catch (err) { console.error("Failed to fetch transactions:", err); }
  };

  const handleCreate = async () => {
    if (!newName.trim()) return;
    try {
      const newStmt = await statementService.createManualStatement(newName);
      setStatements(prev => [newStmt, ...prev]);
      setNewName("");
      setIsCreating(false);
      handleSelect(newStmt);
    } catch (err) { alert("Failed to create ledger."); }
  };

  // UPDATED: Handles single entries AND recurring month loops securely
  const handleAdd = async (e, isRecurring, recurMonths) => {
    e.preventDefault();
    if (!formData.transaction_date || !formData.vendor_raw || !formData.amount || !formData.category) return;

    // Parse date safely to avoid TimeZone shifting issues
    const [year, month, day] = formData.transaction_date.split('-').map(Number);
    const monthsToProcess = isRecurring ? recurMonths : 1;

    try {
      for (let i = 0; i < monthsToProcess; i++) {
        let m = month + i;
        let y = year;
        
        // Handle year rollover (e.g. Nov + 3 months = Feb next year)
        while (m > 12) {
          m -= 12;
          y += 1;
        }
        
        const dateString = `${y}-${m.toString().padStart(2, '0')}-${day.toString().padStart(2, '0')}`;
        
        const payload = {
          statement_id: selectedStatement.id,
          transaction_date: dateString,
          vendor_raw: formData.vendor_raw,
          amount: parseFloat(formData.amount),
          category: formData.category
        };
        await transactionService.addManualTransaction(payload);
      }

      // Refresh to see all generated transactions
      const freshData = await statementService.getStatementTransactions(selectedStatement.id);
      setTransactions(freshData);
      setFormData({ ...formData, vendor_raw: '', amount: '', category: '' });
      
    } catch (err) { alert("Addition failed. Check inputs."); }
  };

  // NEW: Legacy Excel/CSV Importer
  const handleImportCSV = (e) => {
    const file = e.target.files[0];
    if (!file) return;

    const yearInput = prompt("Enter the Year for this legacy spreadsheet (e.g., 2024):", new Date().getFullYear() - 1);
    if (!yearInput) {
      e.target.value = null; 
      return;
    }
    const year = parseInt(yearInput, 10);

    const reader = new FileReader();
    reader.onload = async (event) => {
      const text = event.target.result;
      
      // Regex correctly splits CSVs generated by Excel (handling commas inside quoted numbers like "1,200.00")
      const parseCSVLine = (line) => {
          const re = /,(?=(?:(?:[^"]*"){2})*[^"]*$)/;
          return line.split(re).map(s => s.replace(/(^"|"$)/g, '').trim());
      };

      const lines = text.split('\n').filter(l => l.trim() !== '');
      const transactionsToCreate = [];

      // Loop through rows. Assume Row 0 is Headers.
      // Columns expected: 0=Category, 1=Jan, 2=Feb ... 12=Dec
      for (let i = 1; i < lines.length; i++) {
          const cols = parseCSVLine(lines[i]);
          if (cols.length < 13) continue; // Skip malformed rows

          const categoryName = cols[0];
          if (!categoryName) continue;

          // Loop through the 12 month columns
          for (let m = 1; m <= 12; m++) {
              const valStr = cols[m];
              if (!valStr) continue;
              
              // Strip $, commas, and spaces safely
              const cleanVal = valStr.replace(/[^0-9.-]+/g, "");
              const amount = parseFloat(cleanVal);

              if (!isNaN(amount) && amount > 0) {
                  const monthStr = m.toString().padStart(2, '0');
                  transactionsToCreate.push({
                      statement_id: selectedStatement.id,
                      transaction_date: `${year}-${monthStr}-01`, // Default to 1st of the month
                      vendor_raw: categoryName, // Use row name as vendor
                      category: categoryName,   // Use row name as category
                      amount: amount
                  });
              }
          }
      }

      if (transactionsToCreate.length === 0) {
          alert("No valid data found. Please ensure it is saved as a CSV formatted as: Category | Jan | Feb | ... | Dec");
          e.target.value = null;
          return;
      }

      if (confirm(`Found ${transactionsToCreate.length} valid entries for ${year}. Ready to import?`)) {
          try {
              // Sequentially fire them to the backend to prevent API choking
              for (const tx of transactionsToCreate) {
                   await transactionService.addManualTransaction(tx);
              }
              const freshData = await statementService.getStatementTransactions(selectedStatement.id);
              setTransactions(freshData);
              alert("Legacy Import Successful!");
          } catch (err) {
              console.error(err);
              alert("Some transactions failed to import.");
          }
      }
      e.target.value = null;
    };
    reader.readAsText(file);
  };

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this transaction?")) {
      await transactionService.deleteTransaction(id);
      setTransactions(transactions.filter(t => t.id !== id));
    }
  };

  const handleUpdate = async (id, updatedFields) => {
    try {
      const payload = { ...updatedFields, amount: parseFloat(updatedFields.amount) };
      const updatedTx = await transactionService.updateManualTransaction(id, payload);
      setTransactions(transactions.map(t => t.id === id ? updatedTx : t));
    } catch (err) { alert("Update failed."); }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      <StatementSelector
        statements={statements} selectedId={selectedStatement?.id} onSelect={handleSelect}
        onToggleCreate={() => setIsCreating(!isCreating)} isCreating={isCreating}
        newName={newName} setNewName={setNewName} onCreate={handleCreate}
      />
      {selectedStatement && (
        <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
          
          {/* NEW: Legacy Import Banner */}
          <div className="flex justify-between items-center bg-blue-50/50 p-4 rounded-2xl border border-blue-100">
             <div>
                <h4 className="text-sm font-bold text-gray-800">Legacy Data Import</h4>
                <p className="text-xs text-gray-500 mt-0.5">Upload a CSV saved from Excel. Expected columns: <b>Category | Jan | Feb | ... | Dec</b></p>
             </div>
             <label className="cursor-pointer bg-white border border-blue-200 text-blue-700 px-4 py-2.5 rounded-xl text-xs font-black uppercase tracking-widest hover:bg-blue-600 hover:text-white hover:border-blue-600 transition-all flex items-center gap-2 shadow-sm">
                <UploadCloud size={16} /> Import CSV
                <input type="file" accept=".csv" className="hidden" onChange={handleImportCSV} />
             </label>
          </div>

          <LedgerForm formData={formData} categories={categories} onChange={setFormData} onSubmit={handleAdd} />
          
          <TransactionTable
            transactions={transactions}
            onDelete={handleDelete}
            onUpdate={handleUpdate}
          />
        </div>
      )}
    </div>
  );
}